# Generated by Django 5.2 on 2025-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='img',
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
